### ISSUE TITLE
error trying to get data by software version "[Errno 403] <h1>Developer Over Rate</h1>"

### ISSUE THREAD

**Issue by jcsjacobs** [CiscoPSIRT/openVulnQuery#20]
Hello,

Since 18 september when I try to run the get_by_ios_xe or get_by_nxos I get the error

    advisories = query_client.get_by_ios_xe('default', ios_version=sw_version)
  File "C:\Users\jacob485\AppData\Local\Programs\Python\Python38-32\lib\site-packages\openVulnQuery\_library\query_client.py", line 156, in get_by_ios_xe
    raise requests.exceptions.HTTPError(
requests.exceptions.HTTPError: [Errno 403] <h1>Developer Over Rate</h1>

Now I also notices that you added support for the asa and ftd but I cant download this new version, I still have the old 1.31 version code

hope you can help with this.

**Comment by jcsjacobs** [comment]
I just found out that the rate limits are changed??
it was:
Rate Limits
 10    Calls per second
 5,000    Calls per day
 
 it now is 
 Rate Limits
 2    Calls per second
 3    Calls per minute

**Comment by poxman** [comment]
The quota limits where changed to 2 per second, 10 calls per minute with a maximum of 5,000 per day on 1st October 2022.  The error code now would respond with a 429 rather than a 403.

requests.exceptions.HTTPError: [Errno 429] <h1>Developer Over Rate</h1>

Put rate limiting in your code on calling query_client

**Comment by santosomar** [comment]
Additional information at: https://community.cisco.com/t5/services-discussions/api-rate-limiting-best-practices/td-p/4819009
