### ISSUE TITLE
get_by_nxos will return first_fixed with None

### ISSUE THREAD

**Issue by qifawu** [CiscoPSIRT/openVulnQuery#23]
Hi,

I tried get_by_nxos and noticed that the advisories always had "first_fixed" with None . 
```
ad_nxos = query.get_by_nxos('nxos', '7.3(3)N1(1)')
```

In order to troubleshoot this, I used get_request to fetch the raw API output for both ios and nxos:
```
ad_iosxe = query.get_request('iosxe', params={'version':'3.16.1S'})
ad_nxos = query.get_request('nxos', params={'version':'7.3(3)N1(1)'})
```

From the results, the raw outputs of each ios advisory has the key called "firstFixed":
```
{
    'advisoryId' = {str} 'cisco-sa-appnav-xe-dos-j5MXTR4'
     ...
    'firstFixed' = {list: 1} ['16.12.6']
     ...
}
```

Instead, the raw output of each nxos advisory has the key "platforms", which contains the 'firstFixes':
```
{
    'advisoryId' = {str} 'cisco-sa-nxos-cdp-dos-ce-wWvPucC9'
    ...
    'platforms' = {list: 2} [
          {'id': '265090', 'name': 'Cisco Nexus 5000 Series Switches', 'firstFixes': [{'id': '289274', 'name': '7.3(12)N1(1)'}], 'vulnerabilityState': 'vulnerable'}, 
          {'id': '265094', 'name': 'Cisco Nexus 6000 Series Switches', 'firstFixes': [{'id': '289274', 'name': '7.3(12)N1(1)'}], 'vulnerabilityState': 'vulnerable'}
     ]
     ...
}
```

I think the reason for the issue lies in no code logic handling nxos outputs in advisory.py. The temporary workaround is to use get_request and get firstFixes manually.

**Comment by poxman** [comment]
> Hi,
> 
> I tried get_by_nxos and noticed that the advisories always had "first_fixed" with None .
> 
> ```
> ad_nxos = query.get_by_nxos('nxos', '7.3(3)N1(1)')
> ```
> 
> In order to troubleshoot this, I used get_request to fetch the raw API output for both ios and nxos:
> 
> ```
> ad_iosxe = query.get_request('iosxe', params={'version':'3.16.1S'})
> ad_nxos = query.get_request('nxos', params={'version':'7.3(3)N1(1)'})
> ```
> 
> From the results, the raw outputs of each ios advisory has the key called "firstFixed":
> 
> ```
> {
>     'advisoryId' = {str} 'cisco-sa-appnav-xe-dos-j5MXTR4'
>      ...
>     'firstFixed' = {list: 1} ['16.12.6']
>      ...
> }
> ```
> 
> Instead, the raw output of each nxos advisory has the key "platforms", which contains the 'firstFixes':
> 
> ```
> {
>     'advisoryId' = {str} 'cisco-sa-nxos-cdp-dos-ce-wWvPucC9'
>     ...
>     'platforms' = {list: 2} [
>           {'id': '265090', 'name': 'Cisco Nexus 5000 Series Switches', 'firstFixes': [{'id': '289274', 'name': '7.3(12)N1(1)'}], 'vulnerabilityState': 'vulnerable'}, 
>           {'id': '265094', 'name': 'Cisco Nexus 6000 Series Switches', 'firstFixes': [{'id': '289274', 'name': '7.3(12)N1(1)'}], 'vulnerabilityState': 'vulnerable'}
>      ]
>      ...
> }
> ```
> 
> I think the reason for the issue lies in no code logic handling nxos outputs in advisory.py. The temporary workaround is to use get_request and get firstFixes manually.

Thanks @qifawu 

Cisco IOS and Cisco IOS XE doesn’t have the concept of platform, it is a single product.  NX-OS,ACI, ASA, etc have the additional fields of platform and hence a first fix release based on per platform rather than just the operating system.
 
You can define a filter for the platformAlias: example:
 
>>> filter = query_client.OptionalParameters(query_client.PLATFORMALIAS,'NEXUS9000')
>>> ad_nxos = client.get_by_nxos('default','7.0(3)I6(2)',filter)
 
If you wish to obtain the first fix for each:
>>> for item in ad_nxos:
...   print(item.advisory_title)
...   for platform in item.platforms:
...     print("  " + platform.name,end=":")
...     for fix in platform.firstFixes:
...       print(fix['name'])
...
Cisco NX-OS Software MPLS OAM Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(10)
Cisco FXOS and NX-OS Software Cisco Discovery Protocol Denial of Service and Arbitrary Code Execution Vulnerability
  Cisco Nexus 9000 Series Switches:9.3(10)
Cisco NX-OS Software OSPFv3 Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:9.3(9)
Cisco Nexus 9000 Series Switches Bidirectional Forwarding Detection Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:9.3(9)
Cisco FXOS and NX-OS Software Cisco Discovery Protocol Service Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:9.3(9)
Cisco NX-OS Software Cisco Fabric Services Over IP Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:9.3(9)
Cisco NX-OS Software NX-API Command Injection Vulnerability
  Cisco Nexus 9000 Series Switches:9.3(9)
Multiple Cisco Operating Systems Unidirectional Link Detection Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(10)
Cisco FXOS and NX-OS Software Unidirectional Link Detection Denial of Service and Arbitrary Code Execution Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(10)
Cisco NX-OS Software IPv6 Netstack Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(9)
Cisco NX-OS Software NX-API Cross-Site Request Forgery Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(9)
Cisco FXOS and NX-OS Software Cisco Fabric Services Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(9)
Cisco NX-OS Software Data Management Engine Remote Code Execution Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(8)
Cisco NX-OS Software Call Home Command Injection Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(2)
Cisco NX-OS Software IPv6 Protocol Independent Multicast Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(8)
Cisco IOS, IOS XE, IOS XR, and NX-OS Software One Platform Kit Remote Code Execution Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(8)
Cisco FXOS, IOS XR, and NX-OS Software Cisco Discovery Protocol Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(8)
Cisco NX-OS Software Cisco Fabric Services over IP Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(4)
Cisco FXOS and NX-OS Software Authenticated Simple Network Management Protocol Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(6)
Cisco NX-OS Software Remote Management Memory Leak Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(4)
Cisco NX-OS Software Network Time Protocol Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(6)
Cisco NX-OS Software Virtualization Manager Command Injection Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(6)
Cisco NX-OS Software NX-API Denial of Service Vulnerability
  Cisco Nexus 9000 Series Switches:7.0(3)I7(6)
>>> 
 
 
Output without a filter defined:
 
Cisco NX-OS Software MPLS OAM Denial of Service Vulnerability
  Cisco Nexus 3000 Series Switches:7.0(3)I7(10)
  Cisco Nexus 9000 Series Switches:7.0(3)I7(10)
Cisco FXOS and NX-OS Software Cisco Discovery Protocol Denial of Service and Arbitrary Code Execution Vulnerability
  Cisco Nexus 3000 Series Switches:9.3(10)
 Cisco Nexus 9000 Series Switches:9.3(10)
.
.
.
 
HTH.  If need more qualification on this please pop an email to openvuln@cisco.com
