### ISSUE TITLE
Client ID vs. Key

### ISSUE THREAD

**Issue by mrdos010** [CiscoPSIRT/openVulnQuery#5]
Hi,

it's about the Cisco PSIRT openVuln API.
Could you please differentiate between Client ID and Key? or is it meant the same? In the API Console I only see Key and Secret ID but no Client ID. Thanks!

**Comment by santosomar** [comment]
Hi @mrdos010 ,

You will need a client ID and a client secret. The Cisco PSIRT openVuln API applications require an API "access token" in order to authenticate each individual API request. To generate such an access token (typically performed upon startup, or just prior to accessing the API), the application performs an [OAuth2 client credentials grant flow](https://tools.ietf.org/html/rfc6749#section-1.3.4). Registering an application with the [Cisco API Developer Portal](https://apiconsole.cisco.com/) generates all the details needed to successfully complete the authentication sequence. The registration process creates the client credentials along with name assignment, description, and subscribes the client application to one or more of the OAuth v2.0 grant types requested for their client application.

**Comment by mrdos010** [comment]
Hello Omar,  many thanks for your Replay.

Unfortunately i can't see any Client ID after registering a new APP :/

am i missing anything?

![image](https://user-images.githubusercontent.com/41289973/115870202-355b4180-a43f-11eb-858d-2c5b88cef5ac.png)
